### ISSUE TITLE
training with prune throws exception

### ISSUE THREAD

**Issue by tawnkramer** [tawnkramer/donkey#8]
Tom, training with prune enabled, all options set to default, I eventually hit this exception:

note, I do have the latest kerassurgeon from source, not pip package install.

Here's just the exception part. I will include the entire log separately.
[train_log.txt](https://github.com/tawnkramer/donkey/files/2829212/train_log.txt)

++++++++++++++++++++++++++

Deleting 3/24 channels from layer: conv2d_1
Traceback (most recent call last):
  File "D:\Miniconda3\envs\donkey\lib\site-packages\keras\engine\base_layer.py", line 279, in assert_input_compatibility
    K.is_keras_tensor(x)
  File "D:\Miniconda3\envs\donkey\lib\site-packages\keras\backend\tensorflow_backend.py", line 474, in is_keras_tensor
    str(type(x)) + '`. '
ValueError: Unexpectedly found an instance of type `<class 'NoneType'>`. Expected a symbolic tensor instance.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 524, in <module>
    multi_train(cfg, tub, model, transfer, model_type, continuous, aug)
  File "D:\d2\train.py", line 875, in multi_train
    train_fn(cfg, tub, model, transfer, model_type, continuous, aug)
  File "D:\d2\train.py", line 520, in train
    go_train(kl, cfg, train_gen, val_gen, gen_records, model_name, steps_per_epoch, val_steps, continuous, verbose, save_best)
  File "D:\d2\train.py", line 607, in go_train
    model, channels_deleted = prune(kl.model, prune_gen, 1, cfg)
  File "D:\d2\train.py", line 885, in prune
    model = prune_model(model, apoz_df, n_channels_delete)
  File "D:\d2\train.py", line 911, in prune_model
    return surgeon.operate()
  File "c:\cygwin\home\tkramer\projects\keras-surgeon\src\kerassurgeon\surgeon.py", line 158, in operate
    self._mod_func_map[node](node, outputs, output_masks, **kwargs)
  File "c:\cygwin\home\tkramer\projects\keras-surgeon\src\kerassurgeon\surgeon.py", line 323, in _delete_channels
    temp_layer(utils.single_element(inputs))
  File "D:\Miniconda3\envs\donkey\lib\site-packages\keras\engine\base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "D:\Miniconda3\envs\donkey\lib\site-packages\keras\engine\base_layer.py", line 285, in assert_input_compatibility
    str(inputs) + '. All inputs to the layer '
ValueError: Layer conv2d_3 was called with an input that isn't a symbolic tensor. Received type: <class 'NoneType'>. Full input: [None]. All inputs to the layer should be tensors.

**Comment by tawnkramer** [comment]
Here's a copy of config.py. Data was @10K records from the simulator.
[config_py.txt](https://github.com/tawnkramer/donkey/files/2829220/config_py.txt)

**Comment by blown302** [comment]
What version of TF/Keras do you have?

**Comment by tawnkramer** [comment]
looks like it was related to some integer math

**Comment by tawnkramer** [comment]
fixed now.
